// <auto-generated />
namespace WebLogin1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Agrego_Columna_Nacimiento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agrego_Columna_Nacimiento));
        
        string IMigrationMetadata.Id
        {
            get { return "202212040245133_Agrego_Columna_Nacimiento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
